# Generated by Django 3.0.6 on 2020-05-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20200519_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Make task public? (Your task will be publicly available for everyone to view, but not edit)'),
        ),
    ]
