# Generated by Django 3.0.6 on 2020-07-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20200519_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='duedate',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Duedate (YYYY-MM-DD HH:MM)'),
        ),
    ]
