version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432'

  web:
    build: .
    command: gunicorn todo_tracker.wsgi
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

  redis:
    image: "redis:latest"

  celery:
    build: .
    command: celery -A todo_tracker worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
      
volumes:
  postgres_data:
