# Generated by Django 3.0.6 on 2020-05-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
